# all PID gains are in the format [kp, ki, kd]
pid-gains:
  pos-ctrl:
    x: [0.2, 0.000, 0.05]
    y: [0.2, 0.000, 0.05]
    z: [1, 0.01, 0.3]
    yaw: [0.3, 0, 0.01]
  rate-ctrl:
    x: [0, 0, 0]
    y: [0, 0, 0]
    z: [0, 0, 0]
    ems-z: [0, 0, 0]

# rate saturation limits for each position controller are in the format of [upper, lower]
limits:
  rate: # limits are m/s for x, y, z and rad/s for yaw
    x: [1, -1]
    y: [1, -1]
    z: [0.5, -0.5]
    yaw: [0.2, -0.2]
  accel: # limits are m/s^2
    x: [5, -5]
    y: [5, -5]
    z: [1, -1]
  angle: # limits are in degrees
    roll:  [10, -10]
    pitch: [10, -10]
  thrust: [1, 0]
  
# vehicle params that won't be tuned
uart-path: "/dev/ttyACM1"
#true - Sets the incoming path start time to current state time, false - Uses time in path_t message
reset-path-starts: true
sim-state: false             #true - state comes from sim, false - state comes from kalman filter
ff-thrust: 0.0                
arming-delay: 1             #seconds
land-detect-dur: 0.5

tol: 0.10                   # convergence tolerance (norm of [x, y, z, yaw])
takeoff-alt: 1              #meters
takeoff-speed: 0.3
landing-speed: 0.3
flight-speed: 0.5


# ZCM publish url
zcm-url: "ipc"
command-zcm-url: "ipc"
# zcm-url: "udpm://239.255.76.67:7667?ttl=1"
# command-zcm-url: "udpm://239.255.76.67:7667?ttl=1"

# Landing detector
z_vel_max: 0.2
xy_vel_max: 1.5
rot_max: 20
throttle_min: 0.12
throttle_hover: 0.4
