  # Configuration file for the kalman filter
# All covariance matrices are diagonal

history:
  size: 300 # Maximum history size
  tolerance: 1000 # [us]

state:
  # Starting state
  attitude: [1, 0, 0, 0]
  position: [0, 0, 0] # [m]
  velocity: [0, 0, 0] # [m/s]

  # Starting covariance
  covariance: [0.00001, 0.00001, 0.00001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001]


prediction:
  # Unscented transform params
  UT:
    alpha: 0.05
    beta: 2.0
    kappa: 2

  # Process noise covariance
  Q_i: [0.00005, 0.00005, 0.00005, 0.00002, 0.00002, 0.00002, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001]

imu_extrinsics:
  rot: [1, 0, 0, 0]
  pos: [0, 0.0, -0.16]

updates:
  imu_height: 0.17

  lidar:
    enabled: false
    enable_outliers: true
    # Unscented transform params
    UT:
      alpha: 0.1
      beta: 2.0
      kappa: 0.0
    # Sensor noise covariance
    R: [0.01]
    # Pose relative to IMU
    extrinsics:
      rot: [1, 0, 0, 0]
      pos: [-0.04, 0.07, 0.07]
    # Calibrated
    lidar_bias: 0.075

  planefit:
    enabled: false
    enable_outliers: true
    # Unscented transform params
    UT:
      alpha: 0.1
      beta: 2.0
      kappa: 0.0
    # Sensor noise covariance
    R: [0.000001, 0.000001, 0.000001, 0.000001]
    # Pose relative to IMU
    extrinsics:
      rot: [1, 0, 0, 0]
      pos: [0.04, -0.07, 0.06]

  global_update:
    enabled: true
    enable_outliers: false
    # Unscented transform params
    UT:
      alpha: 0.1
      beta: 2.0
      kappa: 0.0
    # Sensor noise covariance
    R: [0.00001, 0.00001, 0.00001, 0.0003, 0.0003, 0.0003]
    # Pose relative to IMU
    extrinsics:
      rot: [1, 0, 0, 0]
      pos: [0.12, 0, 0]

sim_imu: false
sim_lidar: false
sim_planefit: false
sim_global_update: false

