# Configuration file for the kalman filter
# All covariance matrices are diagonal

history:
  size: 300 # Maximum history size
  tolerance: 1000 # [us]

state:
  # Starting state
  attitude: [1, 0, 0, 0]
  position: [0, 0, 0] # [m]
  velocity: [0, 0, 0] # [m/s]

  # Starting covariance
  covariance: [0.000001, 0.000001, 0.000001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001]


prediction:
  # Unscented transform params
  UT:
    alpha: 0.1
    beta: 2.0
    kappa: 2

  # Process noise covariance
  Q_i: [0.000001, 0.000001, 0.000001, 0.0001, 0.00001, 0.00001]

updates:

  lidar:
    # Unscented transform params
    UT:
      alpha: 0.1
      beta: 2.0
      kappa: 0.0

    # Sensor noise covariance
    R: [0.000001]

  planefit:
    # Unscented transform params
    UT:
      alpha: 0.1
      beta: 2.0
      kappa: 0.0

    # Sensor noise covariance
    R: [0.000001, 0.000001, 0.000001, 0.000001]
