# Configuration file for the kalman filter
# All covariance matrices are diagonal

history:
  size: 300 # Maximum history size
  tolerance: 1000 # [us]

state:
  # Starting state
  attitude: [1, 0, 0, 0]
  position: [0, 0, 0] # [m]
  velocity: [0, 0, 0] # [m/s]

  # Starting covariance
  covariance: [0.00001, 0.00001, 0.00001, 0.001, 0.001, 0.001, 0.000001, 0.000001, 0.000001]


prediction:
  # Unscented transform params
  UT:
    alpha: 0.05
    beta: 2.0
    kappa: 2

  # Process noise covariance
  Q_i: [0.00001, 0.00001, 0.00001, 0.0001, 0.0001, 0.0001]

updates:

  lidar:
    enabled: true
    # Unscented transform params
    UT:
      alpha: 0.1
      beta: 2.0
      kappa: 0.0
    # Sensor noise covariance
    R: [0.00001]
    # Pose relative to IMU
    extrinsics:
      rot: [1, 0, 0, 0]
      pos: [0, 0, 0]

  planefit:
    enabled: false
    # Unscented transform params
    UT:
      alpha: 0.1
      beta: 2.0
      kappa: 0.0
    # Sensor noise covariance
    R: [0.000001, 0.000001, 0.000001, 0.000001]
    # Pose relative to IMU
    extrinsics:
      rot: [1, 0, 0, 0]
      pos: [0, 0, 0]

  global_update:
    enabled: true
    # Unscented transform params
    UT:
      alpha: 0.1
      beta: 2.0
      kappa: 0.0
    # Sensor noise covariance
    R: [0.00001, 0.00001, 0.00001, 0.0005, 0.0005, 0.01]
    # Pose relative to IMU
    extrinsics:
      rot: [1, 0, 0, 0]
      pos: [0, 0, 0]

sim_imu: false
sim_lidar: false
sim_planefit: false
sim_global_update: false

