# Set test path for quad to run through
# waypoint format is [x, y, z, heading]
# write waypoints as a sequential list of integers
#   to support reading them into a path in maav-controller
#   skipping numbers or providing non integer values will
#   cause the path to not be read properly

path:
  0: [0, 0, -2, 0]
  1: [0, 0, -2, 0]
  2: [2, 0, -2, 0]
  3: [2, 0, -2, 90]
  4: [2, 2, -2, 90]
  5: [2, 2, -2, 180]
  6: [-2, 2, -2, 180]
  7: [-2, 2, -2, -90]
  8: [-2, -2, -2, -90]
  9: [-2, -2, -2, 0]
  10: [2, -2, -2, 0]
  11: [2, -2, -2, 90]
  12: [2, 0, -2, 90]
  13: [2, 0, -2, 180]
  14: [0, 0, -2, 180]
  15: [0, 0, -2, 0]