# Set test path for quad to run through
# waypoint format is [x, y, z, heading]
# write waypoints as a sequential list of integers
#   to support reading them into a path in maav-controller
#   skipping numbers or providing non integer values will
#   cause the path to not be read properly

path:
  0: [0, 0, -2, 0]
  1: [1, 0, -2, 0]
  2: [-1, 0, -2, 0]
  3: [-1, 0, -2, 45]
  4: [0, 1, -2, 45]
  5: [1, 2, -2, 45]
  6: [0, 0, -2, 0]
  7: [0, 0, 0, 0]