# all PID gains are in the format [kp, ki, kd]
pid-gains:
  pos-ctrl:
    x: [1, 0, 0]
    y: [1, 0, 0]
    z: [3, 0, 0]
    yaw: [1, 0, 0]
  rate-ctrl:
    x: [1, 0, 0]
    y: [1, 0, 0]
    z: [1, 0.001, -0.05]

# rate saturation limits for each position controller are in the format of [upper, lower]
limits:
  rate: # limits are m/s for x, y, z and rad/s for yaw
    x: [3, -3]
    y: [3, -3]
    z: [3, -3]
  accel: # limits are m/s^2
    x: [5, -5]
    y: [5, -5]
    z: [5, -5]
  angle: # limits are in degrees
    pitch: [10, -10]
    roll: [10, -10]
    yaw: [5, -5]

# vehicle params that won't be tuned
mass: 3.0 # kg
tol: 0.01 # convergence tolerance (norm of [x, y, z, yaw])
min-fnorm: 0.001 # minimum allowed body-force norm (L2) on the vehicle: || [Fx, Fy, Fz] ||

uart-path: "/dev/ttyACM1"
min-thrust: 0
