# Camera parameters

forward:
  width: 640
  height: 480
  fps: 30                # 15, 30, or 60
  serial: "805212060548" # 12 digit number on bottom of realsense camera

downward:
  width: 640
  height: 480
  fps: 30                # 15, 30, or 60
  serial: "817512071338" # 12 digit number on bottom of realsense camera
