#Config file for localization
x_init: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0] # [pos, quat, vel]

P_init_scalar: 1.0

tracker_size: 300

num_cam: 5

label_weights: # order matters!
 - 0.01 # Green Corner
 - 0.01 # Red Corner
 - 0.10 # Green Edge
 - 0.10 # Red Edge
 - 0.20 # Green Edge Uncertain
 - 0.20 # Red Edge Uncertain
 - 0.50 # White Edge
 - 0.50 # White Edge Uncertain
 - 1.50 # White Interior

Rvision: # in camera order!
 - [[0.0001, 0], [0, 0.001]]
 - [[0.0001, 0], [0, 0.001]]
 - [[0.0001, 0], [0, 0.001]]
 - [[0.0001, 0], [0, 0.001]]
 - [[0.0001, 0], [0, 0.001]]

Rlidar: 0.01 # 1d

Rplane: 
- [0.005,       0]
- [    0,   0.005]

Rvo: 
- [0.01,    0,    0,    0,    0,    0,    0,    0,    0]
- [   0, 0.01,    0,    0,    0,    0,    0,    0,    0]
- [   0,    0, 0.01,    0,    0,    0,    0,    0,    0]
- [   0,    0,    0, 0.01,    0,    0,    0,    0,    0]
- [   0,    0,    0,    0, 0.01,    0,    0,    0,    0]
- [   0,    0,    0,    0,    0, 0.01,    0,    0,    0]
- [   0,    0,    0,    0,    0,    0, 0.01,    0,    0]
- [   0,    0,    0,    0,    0,    0,    0, 0.01,    0]
- [   0,    0,    0,    0,    0,    0,    0,    0, 0.01]

Q:
- [.1,   0,     0,      0,      0,      0]
- [0,   .1,     0,      0,      0,      0]
- [0,     0,   .1,      0,      0,      0]
- [0,     0,     0,  1.5,      0,      0]
- [0,     0,     0,      0,  1.5,      0]
- [0,     0,     0,      0,      0,  1.5]

bias: [0, 0, 0, 0, 0, 0]

# willow run arena
arena:
- [[0, 0], [0, 6]]
- [[6, 0], [6, 6]]
- [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]
- [[6, 1], [6, 2], [6, 3], [6, 4], [6, 5]]
- [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]
- [[6, 1], [6, 2], [6, 3], [6, 4], [6, 5]]
- [[1, 0], [2, 0], [3, 0], [4, 0], [5, 0], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6]]
- [[1, 0], [2, 0], [3, 0], [4, 0], [5, 0], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6]]
- [[1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5], [5, 1], [5, 2], [5, 3], [5, 4], [5, 5]]

# real arena
#arena:
# - [[ 0, 0], [ 0, 20]] # Green Corner
# - [[20, 0], [20, 20]] # Red Corner
# - [] # Green Edge
# - [] # Red Edgeine 2
# - [] # Green Edge Uncertain
# - [] # Red Edge Uncertain
# - [] # White Edge
# - [] # White Edge Uncertain
# - [] # White Interior

FORMapper:
  Camera0:
    K:
    - [80, 10, 60]      #first row
    - [30, 50, 70]      #2nd row
    - [40, 90, 20]      #3rd row
    Kinv:
    - [0.0147, -0.0144, 0.0064]      #first row
    - [-0.0061, 0.0022, 0.0106]      #2nd row
    - [-0.0019, 0.0189, -0.0103]      #3rd row
    Rc2i:    #Rotation matrix camera to imu
    - [80, 10, 60]      #first row
    - [30, 50, 70]      #2nd row
    - [40, 90, 20]      #3rd row
    Ri2c:
    - [0.0147, -0.0144, 0.0064]      #first row
    - [-0.0061, 0.0022, 0.0106]      #2nd row
    - [-0.0019, 0.0189, -0.0103]      #3rd row
    Tc: [10, 40, 70]          #Camera Translation
    principalPt: [320, 240, 1] #homogenous
  Camera1:
    K:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Kinv:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Rc2i:    #Rotation matrix camera to imu
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Ri2c:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Tc: [0, 0, 0]          #Camera Translation
    principalPt: [320, 240, 1] #homogenous
  Camera2:
    K:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Kinv:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Rc2i:    #Rotation matrix camera to imu
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Ri2c:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Tc: [0, 0, 0]          #Camera Translation
    principalPt: [320, 240, 1] #homogenous
  Camera3:
    K:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Kinv:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Rc2i:    #Rotation matrix camera to imu
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Ri2c:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Tc: [0, 0, 0]          #Camera Translation
    principalPt: [320, 240, 1] #homogenous
  Camera4:
    K:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Kinv:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Rc2i:    #Rotation matrix camera to imu
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Ri2c:
    - [0, 0, 0]      #first row
    - [0, 0, 0]      #2nd row
    - [0, 0, 0]      #3rd row
    Tc: [0, 0, 0]          #Camera Translation
    principalPt: [320, 240, 1] #homogenous
